# Generated by Django 2.0.6 on 2018-12-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Animes',
            },
        ),
        migrations.CreateModel(
            name='AnimeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_id', models.ForeignKey(db_column='anime_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Anime')),
            ],
            options={
                'db_table': 'AnimeDescriptions',
            },
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_id', models.ForeignKey(db_column='anime_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Anime')),
            ],
            options={
                'db_table': 'AnimeGenres',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeOrder', models.IntegerField()),
                ('thumbnail', models.CharField(default='test.jpg', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Episodes',
            },
        ),
        migrations.CreateModel(
            name='EpisodeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_url', models.TextField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Episode')),
            ],
            options={
                'db_table': 'EpisodeVersions',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.CharField(default='test.jpg', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('iso_code', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonOrder', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('startedAiring', models.DateTimeField()),
                ('stoppedAiring', models.DateTimeField(blank=True, null=True)),
                ('poster', models.CharField(default='test.jpg', max_length=250)),
                ('background', models.CharField(default='test.jpg', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_id', models.ForeignKey(db_column='anime_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Anime')),
            ],
            options={
                'db_table': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='SeasonAlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_id', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Season')),
            ],
            options={
                'db_table': 'SeasonAlternativeTitles',
            },
        ),
        migrations.AddField(
            model_name='episodeversion',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_id',
            field=models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Season'),
        ),
        migrations.AddField(
            model_name='animegenre',
            name='genre_id',
            field=models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Genre'),
        ),
        migrations.AddField(
            model_name='animedescription',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language'),
        ),
    ]
