# Generated by Django 2.0.13 on 2019-07-12 09:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Animes',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_order', models.IntegerField()),
                ('thumbnail', models.CharField(blank=True, max_length=250, null=True)),
                ('episode_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Episodes',
            },
        ),
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Episode')),
            ],
            options={
                'db_table': 'EpisodeSubtitles',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre_id', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Genre')),
            ],
            options={
                'db_table': 'GenreTitles',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('iso_code', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_order', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('started_airing', models.DateTimeField()),
                ('stopped_airing', models.DateTimeField(blank=True, null=True)),
                ('poster', models.CharField(blank=True, max_length=250, null=True)),
                ('background', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_id', models.ForeignKey(db_column='anime_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Anime')),
            ],
            options={
                'db_table': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='ReleaseAlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_id', models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Release')),
            ],
            options={
                'db_table': 'ReleaseAlternativeTitles',
            },
        ),
        migrations.CreateModel(
            name='ReleaseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language')),
                ('release_id', models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Release')),
            ],
            options={
                'db_table': 'ReleaseDescriptions',
            },
        ),
        migrations.CreateModel(
            name='ReleaseGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre_id', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Genre')),
                ('release_id', models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Release')),
            ],
            options={
                'db_table': 'ReleaseGenres',
            },
        ),
        migrations.CreateModel(
            name='ReleaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ReleaseType',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='release_type_id',
            field=models.ForeignKey(db_column='release_type_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.ReleaseType'),
        ),
        migrations.AddField(
            model_name='GenreTitle',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language'),
        ),
        migrations.AddField(
            model_name='episodesubtitle',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language'),
        ),
        migrations.AddField(
            model_name='episode',
            name='release_id',
            field=models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Release'),
        ),
    ]
