# Generated by Django 2.0.13 on 2019-07-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='releasetype',
            table='ReleaseTypes',
        ),
    ]
