# Generated by Django 2.0.6 on 2018-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_episode_episodetitle_episodeversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='background',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='stoppedAiring',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
