# Generated by Django 2.0.13 on 2019-07-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_auto_20190712_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
