# Generated by Django 2.0.6 on 2018-12-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_auto_20181211_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language')),
                ('season_id', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Season')),
            ],
            options={
                'db_table': 'SeasonDescriptions',
            },
        ),
        migrations.RemoveField(
            model_name='animedescription',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='animedescription',
            name='language_id',
        ),
        migrations.DeleteModel(
            name='AnimeDescription',
        ),
    ]
