# Generated by Django 2.0.13 on 2019-10-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_auto_20190715_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodesSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Episode')),
            ],
            options={
                'db_table': 'EpisodesSeen',
            },
        ),
    ]
