# Generated by Django 2.0.6 on 2019-01-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_auto_20181224_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='background',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='poster',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
