# Generated by Django 2.0.6 on 2018-11-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_auto_20181116_1334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='season',
            table='Seasons',
        ),
    ]
