# Generated by Django 2.0.6 on 2018-11-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0005_auto_20181116_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonAlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_id', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Season')),
            ],
            options={
                'db_table': 'SeasonAlternativeTitles',
            },
        ),
    ]
