# Generated by Django 2.0.6 on 2019-01-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0005_auto_20190113_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
