# Generated by Django 2.0.6 on 2019-01-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0006_auto_20190114_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre_id', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Genre')),
                ('season_id', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Season')),
            ],
            options={
                'db_table': 'SeasonGenres',
            },
        ),
        migrations.RemoveField(
            model_name='animegenre',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='animegenre',
            name='genre_id',
        ),
        migrations.DeleteModel(
            name='AnimeGenre',
        ),
    ]
