# Generated by Django 2.0.13 on 2019-07-10 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0007_auto_20190120_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EpisodeSubtitles',
            },
        ),
        migrations.CreateModel(
            name='GenreTitleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre_id', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Genre')),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language')),
            ],
            options={
                'db_table': 'GenreTitleVersion',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseOrder', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('movie_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('releaseDate', models.DateTimeField()),
                ('poster', models.CharField(blank=True, max_length=250, null=True)),
                ('background', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_id', models.ForeignKey(db_column='anime_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Anime')),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MovieDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Movie')),
            ],
            options={
                'db_table': 'MovieDescriptions',
            },
        ),
        migrations.CreateModel(
            name='MovieSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Movie')),
            ],
            options={
                'db_table': 'MovieSubtitles',
            },
        ),
        migrations.RemoveField(
            model_name='episodeversion',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='episodeversion',
            name='language_id',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='seasonOrder',
            new_name='releaseOrder',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='EpisodeVersion',
        ),
        migrations.AddField(
            model_name='episodesubtitle',
            name='episode_id',
            field=models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Episode'),
        ),
        migrations.AddField(
            model_name='episodesubtitle',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Language'),
        ),
    ]
