# Generated by Django 2.0.13 on 2019-07-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0009_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='Anime.Movie')),
            ],
            options={
                'db_table': 'MovieAlternativeTitles',
            },
        ),
    ]
