# Generated by Django 2.0.13 on 2019-07-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0010_moviealternativetitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_code',
        ),
        migrations.RemoveField(
            model_name='episodesubtitle',
            name='subtitle_code',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_code',
        ),
        migrations.RemoveField(
            model_name='moviesubtitle',
            name='subtitle_code',
        ),
    ]
