# Generated by Django 2.0.13 on 2019-07-11 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0011_auto_20190711_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='episodesubtitle',
            name='subtitle_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='moviesubtitle',
            name='subtitle_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
